---
version: 0.2.2
slug: tzb-cc2652-flasher
name: TI CC2652 FW Flasher
description: CC2652P 在线更新 加载项插件
url: >
  https://tube0013/tubeszb_addons/tree/master/tzb-cc2652-flasher/
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
gpio: false
hassio_api: true
image: "ghcr.io/tube0013/{arch}-addon-tzb-cc2652-flasher"
init: false
options:
  network_device: null
  device: null
  trigger_esphome_bsl: false
  device_type: false
  flow_control: false
schema:
  device: device(subsystem=tty)?
  network_device: str?
  trigger_esphome_bsl: bool?
  device_type: bool?
  flow_control: bool?
  firmware_url: str?
stage: experimental
startup: once
boot: manual
